# Generated by Django 4.0.7 on 2023-08-16 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheFrag',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('site_id', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('tokens', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
