import importlib
import mimetypes

from django.conf import settings
from django.db.models.fields.files import FieldFile
from django.utils import timezone



try:
    dgs = settings.DJANGOAT_SETTINGS
except:
    raise AttributeError(
        'Please specify a DJANGOAT_SETTINGS module in Django settings (i.e. "main.djangoat" for a settings file "main/djangoat.py")')
try:
    dgs = importlib.import_module(dgs)
except:
    raise ImportError(f'The DJANGOAT_SETTINGS file "{dgs}" could not be imported')



"""
The data dict used with "utils.get_data" and the "data" filter and tag.
"""
DATA = {
    'now': lambda: timezone.now()
}

"""
Settings for the "pager" template tag.
"""
PAGER = {
    'items_per_page': 20,
    'next_text': 'Next »',
    'param': 'page',
    'plus_or_minus': 3,
    'prev_text': '« Prev',
    'throttle_at': None
}

"""
Allows customization of methods used by FieldFile thumbnail methods and template tag thumbnail methods to manage
and display thumbnails. These are as follows:
- get_thumb_html
- get_thumb_url

For example, we might add the following in our DJANGOAT_SETTINGS:

    def get_thumb_url(field_file, key):
        if isinstance(field_file, ImageFieldFile):
            return THIRD_PARTY_THUMB_GENERATOR(field_file, key)
        return THUMB['type_urls'].get(mimetypes.guess_type(field_file)[0], None) or THUMB['type_urls']['default']
     
This presumes that we have per-mimetype images or a default image specified in THUMB['type_urls']. With this in
place, we could then execute the following in our code for a post instance to retrieve an image's thumbnail:

    post_thumb_url = post_instance.image.get_thumb_url(KEY)
    
Or in a template, we could get the url using the following:

    {{ post_instance.image|thumb_url: KEY }}
    
Both of these will return the url generated by the function above. The get_thumb_html works similarly, but returns
html by which to represent the given file instead of a url.
"""
THUMB = {
    'type_html': {  # html per file type; used by default when "get_thumb_html" requests html for a file
        # 'default': '<i class="file-icon"></i>'
        # 'application/pdf': '<i class="pdf-icon"></i>'
    },
    'type_urls': {  # urls per file type; used by default when "get_thumb_url" requests a url for a file
        # 'default': settings.STATIC_URL + 'file.png',
        # 'application/pdf': settings.STATIC_URL + 'pdf.png',
    },
}
if hasattr(dgs, 'THUMB'):
    THUMB['type_html'] = dgs.THUMB.get('type_html', {})
    THUMB['type_urls'] = dgs.THUMB.get('type_urls', {})
FieldFile.get_thumb_html = getattr(dgs, 'get_thumb_html', lambda field_file, key: THUMB['type_html'].get(mimetypes.guess_type(field_file)[0], None) or THUMB['type_html'].get('default', ''))
FieldFile.get_thumb_url = getattr(dgs, 'get_thumb_url', lambda field_file, key: THUMB['type_urls'].get(mimetypes.guess_type(field_file.path)[0], None) or THUMB['type_urls'].get('default', ''))
