from django.db.models.fields.files import FieldFile, ImageFieldFile
from django.utils import timezone



"""
The data dict used with "utils.get_data" and the "data" filter and tag.
"""
DATA = {
    'now': lambda: timezone.now()
}

"""
Settings for the "pager" template tag.
"""
PAGER = {
    'items_per_page': 20,
    'next_text': 'Next »',
    'param': 'page',
    'plus_or_minus': 3,
    'prev_text': '« Prev',
    'throttle_at': None
}

"""
Allows customization of methods used by FieldFile thumbnail methods and template tag thumbnail methods to manage
and display thumbnails. These are as follows:
- get_thumb_html
- get_thumb_url

For example, suppose we do the following in "urls.py" (or somewhere else):

    from djangoat import THUMB
    THUMB['get_thumb_url'] = lambda field_file, key: THIRD_PARTY_THUMB_GENERATOR(field_file, key)

We could then execute the following in our code for a post instance to retrieve an image's thumbnail:

    post_thumb_url = post_instance.image.get_thumb_url(KEY)
    
Or in a template, we could get the url using the following:

    {{ post_instance.image|thumb_url: KEY }}
    
Both of these will return the url generated by the function above. See "django.apps" to see how these will be
registered on startup. All methods will be bound to the FieldFile class, so that they can be executed intuitively
on files, whenever they exist.
"""
from django.conf import settings
THUMB = {
    'get_thumb_html': lambda self, key: f'HTML for {self}',  # a function that returns display html for a thumbnail
    'get_thumb_url': lambda self, key: self.url if self and isinstance(self, ImageFieldFile) else '',  #
    'type_urls': {  # urls to images per non-image file type; used when "get_thumb_url" requests a url for a non-image
        # 'file': settings.STATIC_URL + 'file.png',
        # 'pdf': settings.STATIC_URL + 'pdf.png',
    },
    'type_html': {  # html per non-image file type; used when "get_thumb_html" requests html for a non-image (allows for non-file representations)
        # 'file': '<i class="file-icon"></i>'
        # 'pdf': '<i class="pdf-icon"></i>'
    }
}
# TODO if djangoat.py alongside settings.py; import this in apps.py; based on what we have, update djangoat's functionality
