from django.conf import settings
from django.core.cache import cache
from django.db import models




CACHE_FRAG_KEYS = {}  # store cache keys by CacheFrag (FRAG_NAME, USER_ID, SITE_ID, ARGS_STRING) tuples




# QUERYSETS
class CacheFragQuerySet(models.QuerySet):
    def clear(self):
        """Clears associated content from the cache.

        For example, to clear all CacheFrags associated with a given user, we might use the following.

        ..  code-block:: python

            CacheFrag.object.filter(user_id=12345).clear()

        :return: the queryset
        """
        for cf in self.all():
            cache.delete(cf.key)
        return self




# MODELS
class CacheFrag(models.Model):
    """Provides a means of associating cached content with the key under which it is stored in the cache.

    The primary advantage of storing cache related data in the database is that we can now distinguish different sorts
    of cached content from one another in the admin and directly target those we want to clear. For example, suppose
    we register an admin for this model as shown below (importable via ``djangoat.admin.CacheFragAdmin``):

    ..  code-block:: python

        from djangoat.models import CacheFrag
        from django.contrib import admin


        def clear_cache_frags(modeladmin, request, queryset):
            for cf in queryset:
                cache.delete(cf.key)  # clear cache contents, so it can repopulate on next access
        clear_cache_frags.short_description = 'Clear selected fragments'


        @admin.register(CacheFrag)
        class CacheFragAdmin(admin.ModelAdmin):
            actions = clear_cache_frags,
            list_display = 'name', 'site_id', 'user', 'tokens'
            list_filter = 'name', 'site_id'
            search_fields = 'user__email', 'user__first_name', 'user__last_name', 'tokens'

            def has_add_permission(self, request):
                return False

            def has_change_permission(self, request, obj=None):
                return False

    On the CacheFrag list page, we will now be able to search for and filter on CacheFrag records and clear them
    individually via the cache key associated with each.

    Note that we will also have the option of deleting these records, but deleting a CacheFrag will NOT affect the
    cache, and the record will simply repopulate the next time it's accessed from a template. We should only delete
    CacheFrag records that are no longer in use, so as to declutter the list.
    """
    key = models.CharField(max_length=100, primary_key=True)  # the key returned by Django's "make_template_fragment_key"
    name = models.CharField(max_length=100, db_index=True)
    args = models.CharField(max_length=500, null=True, blank=True)  # a list of args, converted to strings and joined together by "|"
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    site_id = models.PositiveSmallIntegerField(null=True, blank=True, db_index=True)  # use an int field, so as not to require the Sites framework
    date_set = models.DateTimeField(null=True, blank=True)
    duration = models.CharField(max_length=100, null=True, blank=True)  # either numeric seconds until expiration or a date string (i.e. '1d3h')

    objects = CacheFragQuerySet.as_manager()

    def __str__(self):
        return self.name

    @staticmethod
    def get_tuple(name, args=None, user_id=None, site_id=None):
        """
        We keep track of CacheFrag keys via the ``CACHE_FRAG_KEYS`` dict, which is populated on server startup. This
        dict allows us to check if a key for a particular name, user, site, and arguments combination exists and
        retrieve both it and its associated duration string without hitting the database. These fragment keys are
        keyed to the tuple generated by this method.

        In addition to its use within template tags, if we had several particular fragments we wanted to clear and
        know the args, user_id, and site_id combinations that corresponded to them, we could use this method to
        retrieve the keys and clear them all with a single query, as opposed to the multiple it might otherwise take.

        :param name: the name supplied to the cache tag
        :param args: the list of arguments supplied after the fragment name that uniquely identifies this CacheFrag (excluding user_id and site_id)
        :param user_id: the user id gotten from the ``request`` object (applies only to ``usercache`` and ``usersitecache`` tags)
        :param site_id: the site id gotten from the ``settings.SITE_ID`` (applies only to ``sitecache`` and ``usersitecache`` tags)
        :return: a unique tuple of the form (FRAG_NAME, USER_ID, SITE_ID, ARGS_STRING)
        """
        return name, '|'.join(str(a) for a in args) if args else None, user_id, site_id
